### ISSUE TITLE
Threat Found : Trojan:Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by maulikatwork** [TKazer/CS2_External#84]
My Windows Defender is blocking the build and detecting Trojan.
I am oncommit no 124. It was not the case with yesterday's Code.

**Comment by something-0001** [comment]
Disable WD.

Naturally as processes read from memory via external processes, it will be flagged as something suspicious or straight up harmful.

**Comment by 0xE232FE** [comment]
There are other github Repositorys that only provide binarys. They are 100% Infected Viruses and pure Scam. If there would be Malware in Open Source Project. Github is really fast in removing such Scam Repositorys and Accounts. So if CS2_External would be suspicious, it would already be removed.

**Comment by maulikatwork** [comment]
Great Thanks. 
I am not sure why it just started showing up. 
I am using this Exteral ESP since it only had walls and there were no issues from WD.

**Comment by svnkxmza** [comment]
> Great Thanks. I am not sure why it just started showing up. I am using this Exteral ESP since it only had walls and there were no issues from WD.

Because Windows Defender automatically uploads your exe and other files, if they detect some uncommon behavior, they will flag that file. So yesterday it was safe, but today it's unsafe. That's why.

[https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/cloud-protection-microsoft-antivirus-sample-submission?view=o365-worldwide#sample-submission-settings](url)
